-- Frozen copy of the schema as of SCHEMA_VERSION = 1 (commit 23d0b45, phase 2).
--
-- Extracted from git, NOT generated by current code, and never to be regenerated from it.
-- A migration test that builds its "old" database by calling today's init_db is migrating
-- v2 to v2 in six months: it passes while proving nothing. This file is the only thing that
-- keeps the upgrade path honest, so it is append-only -- when SCHEMA_VERSION becomes 3, add
-- schema_v2.sql beside it rather than editing this one.

CREATE TABLE IF NOT EXISTS items (
  id             INTEGER PRIMARY KEY,
  url_hash       TEXT UNIQUE NOT NULL,
  url            TEXT NOT NULL,
  title          TEXT NOT NULL,
  source         TEXT NOT NULL,
  topic          TEXT,
  author         TEXT,
  published_at   TEXT,
  first_seen_at  TEXT NOT NULL,
  raw_json       TEXT,
  score          REAL,
  score_reason   TEXT,
  summary        TEXT,
  digest_date    TEXT,
  feedback       INTEGER DEFAULT 0,
  dupe_of        TEXT
);
CREATE INDEX IF NOT EXISTS idx_items_digest ON items(digest_date);
CREATE INDEX IF NOT EXISTS idx_items_seen   ON items(first_seen_at);
CREATE INDEX IF NOT EXISTS idx_items_dupe   ON items(dupe_of);

CREATE TABLE IF NOT EXISTS sources (
  name                 TEXT PRIMARY KEY,
  kind                 TEXT,
  url                  TEXT,
  etag                 TEXT,
  last_modified        TEXT,
  last_success_at      TEXT,
  consecutive_failures INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS schema_version (version INTEGER NOT NULL);
INSERT INTO schema_version (version) VALUES (1);
